[project]
name = "jintex_customization"
version = "0.0.1"
description = "Stock and Purchase Management"
requires-python = ">=3.10"
readme = "README.md"
dependencies = []

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
