[project]
name = "jintex_customization"
version = "0.0.1"
authors = [
    { name = "Raaj Tailor", email = "raaj@akhilaminc.com"}
]
description = "Stock and Purchase Management"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = "~=15.0.0"
